# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: 
      - master
    paths:
      - Sources
  issues:
    types: [opened, edited]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: swift run -c release gitlog
    - name: Run tests
      run: swift test -v
