# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run gitblog

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - 'Sources/**.swift'

  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: swift run -c release
      env: 
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.token }}
        EVENT_NAME: ${{ github.event_name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        
